issue:
  # Options: Gemini CLI (other options may include Notion in the future)
  provider: "GitHub"
  label: "AI DD"
github:
  # Please set the target repository
  repository: "owner/repository-name"
  # Options: SSH, HTTPS, GitHub CLI
  clone_type: "SSH"
  clone_branch: "main"
  push_branch_on_complete: true
  create_pr_on_complete: true
  pr_draft: false
task:
  list_page_size: 5
ai:
  # Options: Gemini CLI (other options may include Claude Code in the future)
  type: "Gemini CLI"
  # Set when you want to specify the model (e.g., gemini-2.5-pro„ÄÅgemini-2.5-flash)
  model: ""
